on:
  push:
    branches:
      - main

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.inputs.force_publish }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

name: release-please

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test ${{ matrix.rust-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        rust-version:
          - stable
    env:
      HAS_CODECOV_ACCESS: ${{ secrets.CODECOV_TOKEN != '' }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.git_ref || github.ref }}
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust-version }}
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
      - name: Install cargo-llvm-cov
        if: env.HAS_CODECOV_ACCESS == 'true'
        run: cargo install cargo-llvm-cov
      - name: Test compilation
        run: cargo check --all --all-targets
      - name: Test formatting
        run: cargo fmt --all -- --check
      - name: Test clippy
        run: cargo clippy --all --all-targets
      - name: Test documentation
        run: cargo doc --all --no-deps
      - name: Run tests with code coverage
        if: env.HAS_CODECOV_ACCESS == 'true'
        run: cargo llvm-cov --all-features --workspace --codecov --output-path codecov.json
      - name: Upload coverage to Codecov
        if: env.HAS_CODECOV_ACCESS == 'true'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: alanpq/ritobin-lsp
          files: ./codecov.json
          fail_ci_if_error: false
          verbose: true
      - name: Run tests
        if: env.HAS_CODECOV_ACCESS != 'true'
        run: cargo test --all

  release-please:
    name: Execute release chores

    permissions:
      contents: write
      issues: write
      pull-requests: write

    runs-on: ubuntu-latest
    needs: [test]

    outputs:
      created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}

    steps:
      - uses: googleapis/release-please-action@v4
        if: ${{ !github.event.inputs.git_ref }}
        id: release
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

  packaging:
    name: packaging-${{ matrix.platform.target }}
    runs-on: ${{ matrix.platform.os }}
    needs:
      - release-please
    if: needs.release-please.outputs.created
    strategy:
      fail-fast: false
      matrix:
        platform:
          # From https://github.com/houseabsolute/precious/blob/master/.github/workflows/ci.yml
          - os_name: Linux-x86_64
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            bin: lsp-ritobin
            name: lsp-ritobin-Linux-x86_64-musl.tar.gz
          - os_name: Linux-aarch64
            os: ubuntu-latest
            target: aarch64-unknown-linux-musl
            bin: lsp-ritobin
            name: lsp-ritobin-Linux-aarch64-musl.tar.gz
            skip_tests: true
          - os_name: Windows-i686
            os: windows-latest
            target: i686-pc-windows-msvc
            bin: lsp-ritobin.exe
            name: lsp-ritobin-Windows-i686.zip
            skip_tests: true
          - os_name: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: lsp-ritobin.exe
            name: lsp-ritobin-Windows-x86_64.zip
          - os_name: macOS-x86_64
            os: macOS-latest
            target: x86_64-apple-darwin
            bin: lsp-ritobin
            name: lsp-ritobin-macOS-Darwin-x86_64.tar.gz
          - os_name: macOS-aarch64
            os: macOS-latest
            target: aarch64-apple-darwin
            bin: lsp-ritobin
            name: lsp-ritobin-macOS-Darwin-aarch64.tar.gz
            skip_tests: true
        toolchain:
          - stable
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.git_ref || github.ref }}
      - uses: Swatinem/rust-cache@v2
      - name: Install musl-tools on Linux
        run: sudo apt-get update --yes && sudo apt-get install --yes musl-tools
        if: contains(matrix.platform.name, 'musl')
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
            command: "build"
            target: ${{ matrix.platform.target }}
            toolchain: ${{ matrix.toolchain }}
            args: "--locked --release"
            strip: true
      - name: Run tests
        uses: houseabsolute/actions-rust-cross@v0
        with:
            command: "test"
            target: ${{ matrix.platform.target }}
            toolchain: ${{ matrix.toolchain }}
            args: "--locked --release"
        if: ${{ !matrix.platform.skip_tests }}
      - name: Package as archive
        shell: bash
        run: |
            cd target/${{ matrix.platform.target }}/release
            if [[ "${{ matrix.platform.os }}" == "windows-latest" ]]; then
              7z a ../../../${{ matrix.platform.name }} ${{ matrix.platform.bin }}
            else
              tar czvf ../../../${{ matrix.platform.name }} ${{ matrix.platform.bin }}
            fi
            cd -
      - name: Publish release artifacts to GitHub release
        uses: svenstaro/upload-release-action@v2
        if: matrix.toolchain == 'stable'
        with:
          file_glob: true
          tag: ${{ (startsWith(github.event.inputs.git_ref, 'v') && github.event.inputs.git_ref) || needs.release-please.outputs.tag_name }}
          file: ${{ matrix.platform.name }}
          overwrite: true
